//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstWebApplicationTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int m_id { get; set; }
        public string m_fullname { get; set; }
        public string m_email { get; set; }
        public string m_phone { get; set; }
        public string m_detail { get; set; }
        public System.DateTime m_date { get; set; }
    }
}
