//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoGalleryApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoGallery
    {
        public int id { get; set; }
        public string filename { get; set; }
        public string filesize { get; set; }
        public string fileExtension { get; set; }
        public Nullable<System.DateTime> fileAdddate { get; set; }
        public string fileLocation { get; set; }
        public Nullable<int> Catid { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
